import TranslationsProvider from '@/_providers/translation-provider';
import type { Metadata } from 'next';
import { Barlow_Semi_Condensed } from 'next/font/google';
import initTranslations from '../i18n';
import './globals.css';
import { ThemeProvider } from '@/_providers/theme-provider';
import Navbar from '@/components/shared/navbar';
import { TooltipProvider } from '@/components/ui/tooltip';
import AnimatedCursor from "react-animated-cursor"

const barlow = Barlow_Semi_Condensed({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-barlow',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const namespaces = ['hello'];

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { resources } = await initTranslations(locale, namespaces);
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={barlow.className}>
        <TranslationsProvider
          namespaces={namespaces}
          locale={locale}
          resources={resources}
        >
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <AnimatedCursor />
            <TooltipProvider delayDuration={0}>
              <main>{children}</main>
              <Navbar />
            </TooltipProvider>
          </ThemeProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
