import TranslationsProvider from '@/_providers/translation-provider';
import type { Metadata } from 'next';
import { Barlow_Semi_Condensed } from 'next/font/google';
import initTranslations from '../i18n';
import './globals.css';

const barlow = Barlow_Semi_Condensed({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-barlow',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const namespaces = ['hello'];

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { resources } = await initTranslations(locale, namespaces);
  return (
    <html lang={locale}>
      <body className={barlow.className}>
        <TranslationsProvider
          namespaces={namespaces}
          locale={locale}
          resources={resources}
        >
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
